### PR TITLE
1.Make translation easier for Chinese translation

### PR DESCRIPTION
**Pull request by SyaoranChang**
1.Add str variable for menu.newMenu to make translation easier for Chinese translation.

### CODE REVIEW

**Comment by SyaoranChang** [comment]
Hi,
I thought it would be easier to add str for Chinese translations.
Could you adding properly for Chinese translations.

**Comment by Wil-B** [comment]
I came up with these translations using google translate. Can you fix any that are wrong.

```
const ch = {
   "+ Add main image to black list:": "+ 将主图加入黑名单：",
   "+ Add to black list:": "+ 添加到黑名单：",
   "Album": "专辑",
   "Album History:": "专辑历史：",
   "Album view": "相册视图",
   "Align with text": "与文本对齐",
   "Alignment": "结盟",
   "Allmusic biography": "全部音乐传记",
   "Allmusic review": "所有音乐评论",
   "AllMusic:": "全部音乐：",
   "Alt+Click": "Alt+单击",
   "Alt+Middle click": "Alt+中键单击",
   "Amalgamate": "合并",
   "Artist": "艺术家",
   "Artist (single image [fb2k: display])": "艺术家（单幅图像 [fb2k: display]）",
   "Artist History:": "艺术家历史：",
   "Artist view": "艺术家观点",
   "Auto cycle": "自动循环",
   "Auto cycle items": "自动循环项目",
   "Auto lock": "自动锁",
   "Auto-fallback": "自动回退",
   "Back": "后退",
   "Biography [allmusic]": "传记 [所有音乐]",
   "Biography [last.fm]": "传记 [last.fm]",
   "Biography [wikipedia]": "传记[维基百科]",
   "Black list": "黑名单",
   "Bottom": "底部",
   "Centre": "中心",
   "Click": "点击",
   "Cover": "覆盖",
   "Create && manage styles": "创建和管理样式",
   "Create new style...": "创造新风格...",
   "Cycle above": "以上循环",
   "Cycle from custom folder [fallback to above]": "从自定义文件夹循环[回退到上面]",
   "Cycle from download folder": "从下载文件夹循环",
   "Cycle from folder": "从文件夹循环",
   "Delete custom style...": "删除自定义样式...",
   "Disc": "光盘",
   "Display": "展示",
   "Export custom style...": "导出自定义样式...",
   "Filmstrip": "幻灯片",
   "Follow selected track (playlist)": "跟随所选曲目（播放列表）",
   "Force update": "强制性升级",
   "Freestyle": "自由泳",
   "Front": "正面",
   "Heading": "标题",
   "Icon": "图标",
   "Image": "图片",
   "Image ": "图片",
   "Image+text": "图片+文字",
   "Last.fm biography": "Last.fm 传记",
   "Last.fm review": "Last.fm 评论",
   "Last.fm Top Albums:": "Last.fm 热门专辑：",
   "Last.fm:": "最后一个.fm：",
   "Layout": "布局",
   "Left": "剩下",
   "Load": "加载",
   "Manual cycle: wheel over button": "手动循环：滚过按钮",
   "Middle click": "中键单击",
   "More...": "更多的...",
   "N/A - requires last.fm photo. Selected image:": "N/A - 需要 last.fm 照片。 选择的图像：",
   "No black listed images for current artist": "当前艺术家没有列入黑名单的图像",
   "Open file location": "打开文件所在位置",
   "Options...": "选项...",
   "Overlay": "覆盖",
   "Overlay image area": "叠加图像区域",
   "Photo": "照片",
   "Prefer both": "两者都喜欢",
   "Prefer composition reviews (allmusic && wikipedia)": "喜欢作曲评论（allmusic && wikipedia）",
   "Prefer nowplaying": "更喜欢现在播放",
   "Reload": "重新加载",
   "Rename custom style...": "重命名自定义样式...",
   "Reset album history...": "重置专辑历史...",
   "Reset style...": "重置样式...",
   "Reset to default size...": "重置为默认大小...",
   "Reset zoom": "重置缩放",
   "Review [allmusic]": "评论 [所有音乐]",
   "Review [last.fm]": "回顾 [last.fm]",
   "Review [wikipedia]": "评论 [维基百科]",
   "Right": "正确的",
   "Show album history": "显示专辑历史",
   "Show top albums": "显示热门专辑",
   "Show track review options on load menu": "在加载菜单上显示曲目评论选项",
   "Similar Artists:": "类似艺术家：",
   "Sources": "来源",
   "Static": "静止的",
   "Summary": "概括",
   "Text": "文本",
   "Top": "最佳",
   "Track": "追踪",
   "Tracks [allmusic]": "曲目 [所有音乐]",
   "Tracks [last.fm]": "曲目 [last.fm]",
   "Tracks [wikipedia]": "曲目 [维基百科]",
   "Type:": "类型：",
   "Wikipedia biography": "维基百科传记",
   "Wikipedia review": "维基百科评论"
}
```

**Comment by a1waysbeta** [comment]
I also love your Biography and Library-Tree, and did Chinese translations at the same time as your release, with a small release in the fb2k Chinese community. Of course, for me personally, preferring Library-Tree, I did a fork.
Here are my fixes to the translation: (Sorry, I'm not very familiar with the PR feature)
`const ch = {
   "+ Add main image to black list:": "+ 将主图像添加到黑名单：",
   "+ Add to black list:": "+ 添加到黑名单：",
   "Album": "专辑",
   "Album History:": "专辑历史记录：",
   "Album view": "专辑视图",
   "Align with text": "对齐文本",
   "Alignment": "对齐方式",
   "Allmusic biography": "Allmusic 简介",
   "Allmusic review": "Allmusic 评论",
   "AllMusic:": "AllMusic：",
   "Alt+Click": "Alt+单击",
   "Alt+Middle click": "Alt+中键单击",
   "Amalgamate": "合并",
   "Artist": "艺术家",
   "Artist (single image [fb2k: display])": "艺术家（单张图片 [fb2k>参数选项>显示]）",
   "Artist History:": "艺术家历史记录：",
   "Artist view": "艺术家视图",
   "Auto cycle": "自动循环",
   "Auto cycle items": "自动循环项目",
   "Auto lock": "自动锁定",
   "Auto-fallback": "自动回退",
   "Back": "后退",
   "Biography [allmusic]": "简介 [allmusic]",
   "Biography [last.fm]": "简介 [last.fm]",
   "Biography [wikipedia]": "简介 [维基百科]",
   "Black list": "黑名单",
   "Bottom": "下",
   "Centre": "中",
   "Click": "单击",
   "Cover": "封面",
   "Create && manage styles": "创建和管理样式",
   "Create new style...": "创建新样式...",
   "Cycle above": "以上循环",
   "Cycle from custom folder [fallback to above]": "从自定义文件夹循环 [回退到上面]",
   "Cycle from download folder": "从下载文件夹循环",
   "Cycle from folder": "从文件夹循环",
   "Delete custom style...": "删除自定义样式...",
   "Disc": "碟片",
   "Display": "显示",
   "Export custom style...": "导出自定义样式...",
   "Filmstrip": "幻灯片",
   "Follow selected track (playlist)": "跟随所选音轨（播放列表）",
   "Force update": "强制更新",
   "Freestyle": "自由式",
   "Front": "封面",
   "Heading": "标题",
   "Icon": "图标",
   "Image": "图像",
   "Image ": "图像",
   "Image+text": "图像+文本",
   "Last.fm biography": "Last.fm 简介",
   "Last.fm review": "Last.fm 评论",
   "Last.fm Top Albums:": "Last.fm 热门专辑：",
   "Last.fm:": "Last.fm：",
   "Layout": "布局",
   "Left": "左",
   "Load": "加载",
   "Manual cycle: wheel over button": "手动循环：滚动滚轮",
   "Middle click": "中键单击",
   "More...": "更多...",
   "N/A - requires last.fm photo. Selected image:": "不可用 - 需要 Last.fm 照片。所选图像：",
   "No black listed images for current artist": "当前艺术家没有列入黑名单的图像",
   "Open file location": "打开文件位置",
   "Options...": "选项...",
   "Overlay": "叠加",
   "Overlay image area": "叠加图像区域",
   "Photo": "照片",
   "Prefer both": "首选两个",
   "Prefer composition reviews (allmusic && wikipedia)": "首选作品评论（AllMusic 和 维基百科）",
   "Prefer nowplaying": "首选正在播放项",
   "Reload": "重新加载",
   "Rename custom style...": "重命名自定义样式...",
   "Reset album history...": "重置专辑历史记录...",
   "Reset style...": "重置样式...",
   "Reset to default size...": "重置为默认大小...",
   "Reset zoom": "重置缩放",
   "Review [allmusic]": "评论 [AllMusic]",
   "Review [last.fm]": "评论 [Last.fm]",
   "Review [wikipedia]": "评论 [维基百科]",
   "右": "正确的",
   "Show album history": "显示专辑历史记录",
   "Show top albums": "显示热门专辑",
   "Show track review options on load menu": "在加载菜单上显示音轨评论选项",
   "Similar Artists:": "相似艺术家：",
   "Sources": "来源",
   "Static": "静态",
   "Summary": "摘要",
   "Text": "文本",
   "Top": "上",
   "Track": "首",
   "Tracks [allmusic]": "音轨 [AllMusic]",
   "Tracks [last.fm]": "音轨 [Last.fm]",
   "Tracks [wikipedia]": "音轨 [维基百科]",
   "Type:": "样式：",
   "Wikipedia biography": "维基百科简介",
   "Wikipedia review": "维基百科评论"
}`

**Comment by SyaoranChang** [comment]
Hi,

On the [Eole-foobar-theme-CHT](https://github.com/SyaoranChang/Eole-foobar-theme-CHT)
I translated into Traditional Chinese.
Is it possible to switch languages?
To switch Traditional Chinese or Simplified Chinese or other languages.

And about String list.
When use in Album Cover, then "Back": "後面",
or
When use in back to something, then "Back": "返回",
If there is no article before or after, it may not be accurate.

Maybe a1waysbeta translate some words better in simplified Chinese.

Traditional Chinese:
const ch = {
   "+ Add main image to black list:": "+ 加入主要圖片到黑名單：",
   "+ Add to black list:": "+ 加入到黑名單：",
   "Album": "專輯",
   "Album History:": "專輯歷史紀錄：",
   "Album view": "專輯檢視",
   "Align with text": "與文字對齊",
   "Alignment": "對齊方式",
   "Allmusic biography": "所有音效傳記",
   "Allmusic review": "所有音樂評論",
   "AllMusic:": "所有音樂：",
   "Alt+Click": "Alt+點擊",
   "Alt+Middle click": "Alt+點擊中鍵",
   "Amalgamate": "合併",
   "Artist": "表演者",
   "Artist (single image [fb2k: display])": "表演者（單一圖片 [fb2k: display]）",
   "Artist History:": "表演者歷史紀錄：",
   "Artist view": "表演者檢視",
   "Auto cycle": "自動循環",
   "Auto cycle items": "自動循環項目",
   "Auto lock": "自動鎖",
   "Auto-fallback": "自動回退",
   "Back": "後面",
   "Biography [allmusic]": "傳記 [所有音效]",
   "Biography [last.fm]": "傳記 [last.fm]",
   "Biography [wikipedia]": "傳記[維基百科]",
   "Black list": "黑名單",
   "Bottom": "底部",
   "Centre": "中心",
   "Click": "點擊",
   "Cover": "封面",
   "Create && manage styles": "建立和管理樣式",
   "Create new style...": "建立新樣式...",
   "Cycle above": "循環以上",
   "Cycle from custom folder [fallback to above]": "從自訂文件夾循環 [自動退回上面]",
   "Cycle from download folder": "從下載資料夾循環",
   "Cycle from folder": "從資料夾循環",
   "Delete custom style...": "刪除自定義的樣式...",
   "Disc": "光碟",
   "Display": "顯示",
   "Export custom style...": "匯出自定義的樣式...",
   "Filmstrip": "幻燈片",
   "Follow selected track (playlist)": "跟隨選擇的曲目（播放列表）",
   "Force update": "強制更新",
   "Freestyle": "自由風格",
   "Front": "前面",
   "Heading": "標題",
   "Icon": "圖示",
   "Image": "圖片",
   "Image ": "圖片 ",
   "Image+text": "圖片+文字",
   "Last.fm biography": "Last.fm 傳記",
   "Last.fm review": "Last.fm 評論",
   "Last.fm Top Albums:": "Last.fm 熱門專輯：",
   "Last.fm:": "Last.fm：",
   "Layout": "佈局",
   "Left": "左側",
   "Load": "載入",
   "Manual cycle: wheel over button": "手動循環: 滑鼠滾輪按鈕",
   "Middle click": "點擊中鍵",
   "More...": "更多...",
   "N/A - requires last.fm photo. Selected image:": "N/A - 需要 last.fm 照片。 選擇的圖片：",
   "No black listed images for current artist": "目前的表演者沒有黑名單的圖片",
   "Open file location": "開啟所在資料夾",
   "Options...": "設定...",
   "Overlay": "覆蓋",
   "Overlay image area": "疊加圖像區域",
   "Photo": "照片",
   "Prefer both": "兩者都喜歡",
   "Prefer composition reviews (allmusic && wikipedia)": "比較喜歡作品評論（allmusic 和 維基百科）",
   "Prefer nowplaying": "比較喜歡現在播放",
   "Reload": "重新載入",
   "Rename custom style...": "重新命名自定義的樣式...",
   "Reset album history...": "重置專輯歷史紀錄...",
   "Reset style...": "重置樣式...",
   "Reset to default size...": "重置為預設大小...",
   "Reset zoom": "重置縮放",
   "Review [allmusic]": "評論 [allmusic]",
   "Review [last.fm]": "評論 [last.fm]",
   "Review [wikipedia]": "評論 [維基百科]",
   "Right": "右側",
   "Show album history": "顯示專輯歷史紀錄",
   "Show top albums": "顯示熱門專輯",
   "Show track review options on load menu": "在載入選單上顯示曲目評論選項",
   "Similar Artists:": "類似表演者：",
   "Sources": "來源",
   "Static": "靜態",
   "Summary": "摘要",
   "Text": "文字",
   "Top": "頂部",
   "Track": "曲目",
   "Tracks [allmusic]": "曲目 [allmusic]",
   "Tracks [last.fm]": "曲目 [last.fm]",
   "Tracks [wikipedia]": "曲目 [維基百科]",
   "Type:": "類型：",
   "Wikipedia biography": "維基百科 傳記",
   "Wikipedia review": "維基百科 評論"
}

Simplified Chinese
const ch = {
   "+ Add main image to black list:": "+ 加入主要图片到黑名单：",
   "+ Add to black list:": "+ 加入到黑名单：",
   "Album": "专辑",
   "Album History:": "专辑历史纪录：",
   "Album view": "专辑查看",
   "Align with text": "与文本对齐",
   "Alignment": "对齐方式",
   "Allmusic biography": "所有音效传记",
   "Allmusic review": "所有音乐评论",
   "AllMusic:": "所有音乐：",
   "Alt+Click": "Alt+点击",
   "Alt+Middle click": "Alt+点击中键",
   "Amalgamate": "合并",
   "Artist": "表演者",
   "Artist (single image [fb2k: display])": "表演者（单一图片 [fb2k: display]）",
   "Artist History:": "表演者历史纪录：",
   "Artist view": "表演者查看",
   "Auto cycle": "自动循环",
   "Auto cycle items": "自动循环项目",
   "Auto lock": "自动锁",
   "Auto-fallback": "自动回退",
   "Back": "后面",
   "Biography [allmusic]": "传记 [所有音效]",
   "Biography [last.fm]": "传记 [last.fm]",
   "Biography [wikipedia]": "传记[维基百科]",
   "Black list": "黑名单",
   "Bottom": "底部",
   "Centre": "中心",
   "Click": "点击",
   "Cover": "封面",
   "Create && manage styles": "创建和管理样式",
   "Create new style...": "创建新样式...",
   "Cycle above": "循环以上",
   "Cycle from custom folder [fallback to above]": "从自订文档夹循环 [自动退回上面]",
   "Cycle from download folder": "从下载文件夹循环",
   "Cycle from folder": "从文件夹循环",
   "Delete custom style...": "删除自定义的样式...",
   "Disc": "光盘",
   "Display": "显示",
   "Export custom style...": "汇出自定义的样式...",
   "Filmstrip": "幻灯片",
   "Follow selected track (playlist)": "跟随选择的曲目（播放列表）",
   "Force update": "强制更新",
   "Freestyle": "自由风格",
   "Front": "前面",
   "Heading": "标题",
   "Icon": "图标",
   "Image": "图片",
   "Image ": "图片 ",
   "Image+text": "图片+文本",
   "Last.fm biography": "Last.fm 传记",
   "Last.fm review": "Last.fm 评论",
   "Last.fm Top Albums:": "Last.fm 热门专辑：",
   "Last.fm:": "Last.fm：",
   "Layout": "布局",
   "Left": "左侧",
   "Load": "加载",
   "Manual cycle: wheel over button": "手动循环: 鼠标滚轮按钮",
   "Middle click": "点击中键",
   "More...": "更多...",
   "N/A - requires last.fm photo. Selected image:": "N/A - 需要 last.fm 照片。 选择的图片：",
   "No black listed images for current artist": "当前的表演者没有黑名单的图片",
   "Open file location": "开启所在文件夹",
   "Options...": "设置...",
   "Overlay": "复盖",
   "Overlay image area": "叠加图象区域",
   "Photo": "照片",
   "Prefer both": "两者都喜欢",
   "Prefer composition reviews (allmusic && wikipedia)": "比较喜欢作品评论（allmusic 和 维基百科）",
   "Prefer nowplaying": "比较喜欢现在播放",
   "Reload": "重新加载",
   "Rename custom style...": "重命名自定义的样式...",
   "Reset album history...": "重置专辑历史纪录...",
   "Reset style...": "重置样式...",
   "Reset to default size...": "重置为缺省大小...",
   "Reset zoom": "重置缩放",
   "Review [allmusic]": "评论 [allmusic]",
   "Review [last.fm]": "评论 [last.fm]",
   "Review [wikipedia]": "评论 [维基百科]",
   "Right": "右侧",
   "Show album history": "显示专辑历史纪录",
   "Show top albums": "显示热门专辑",
   "Show track review options on load menu": "在加载选单上显示曲目评论选项",
   "Similar Artists:": "相似表演者：",
   "Sources": "来源",
   "Static": "静态",
   "Summary": "摘要",
   "Text": "文本",
   "Top": "顶部",
   "Track": "曲目",
   "Tracks [allmusic]": "曲目 [allmusic]",
   "Tracks [last.fm]": "曲目 [last.fm]",
   "Tracks [wikipedia]": "曲目 [维基百科]",
   "Type:": "类型：",
   "Wikipedia biography": "维基百科 传记",
   "Wikipedia review": "维基百科 评论"
}

**Comment by a1waysbeta** [comment]
`presence of spaces is correct as there might be some inconsistencies: e.g., compare with English entries`
In some places: was changed to Chinese's：, so the spaces were removed.
`
const simplifiedChinese = {
    "+ Add to black list: ": "+ 添加到黑名单： ",
    ": N/A no playlist tracks selected": "：不可用，播放列表内未选择音轨",
    "Activate biography": "激活简介",
    "Album": "专辑",
    "Album History:": "专辑历史记录：",
    "album look-up": "查找专辑",
    "Album review [allmusic]": "专辑评论 [AllMusic]",
    "Album review [last.fm]": "专辑评论 [Last.fm]",
    "Album review [wikipedia]": "专辑评论 [维基百科]",
    "Photos [last.fm]": "照片 [last.fm]",
    "Album Unknown": "未知专辑",
    "Album view": "专辑视图",
    "Align with text": "对齐文本",
    "Alignment": "对齐方式",
    "Alignment horizontal": "水平对齐",
    "Alignment vertical": "垂直对齐",
    "All tagger settings...": "标签设置...",
    "Allmusic": "Allmusic",
    "Allmusic:": "Allmusic：",
    "Alt+Click": "Alt+单击",
    "Alt+Middle click": "Alt+中键单击",
    "Amalgamate": "合并",
    "Artist": "艺术家",
    "Artist (single image [fb2k: display])": "艺术家（单张图片 [fb2k>参数选项>显示]）",
    "Artist History:": "艺术家历史记录：",
    "artist look-up": "查找艺术家",
    "Artist Unknown": "未知艺术家",
    "Artist view": "艺术家视图",
    "Auto cycle": "自动循环",
    "Auto cycle items": "自动循环项目",
    "Auto lock": "自动锁定",
    "Auto-fallback": "自动回退",
    "Back": "后退",
    " biography": " 简介",
    "Biography [allmusic]": "简介 [allmusic]",
    "Biography [last.fm]": "简介 [last.fm]",
    "Biography [wikipedia]": "简介 [维基百科]",
    "Biography [allmusic location]": "简介 [AllMusic 位置]",
    "Biography [last.fm location]": "简介 [Last.fm 位置]",
    "Biography [wikipedia location]": "简介 [维基百科位置]",
    "Black list": "黑名单",
    "Bottom": "下",
    "Cancel": "取消",
    "Centre": "中",
    "Click": "单击",
    "composition loaded": "加载作品",
    "Composition Unknown": "未知作品",
    "Configure...": "配置...",
    "Cover": "封面",
    "Create && manage styles": "创建和管理样式",
    "Create new style...": "创建新样式...",
    "Cycle above": "以上循环",
    "Cycle from custom folder [fallback to above]": "从自定义文件夹循环 [回退到上面]",
    "Cycle from download folder": "从下载文件夹循环",
    "Cycle from folder": "从文件夹循环",
    "Delete custom style...": "删除自定义样式...",
    "Disc": "碟片",
    "Display": "显示",
    "Double click": "双击",
    "Export custom style...": "导出自定义样式...",
    "Filmstrip": "幻灯片",
    " first": " 首选",
    "Follow selected track: N/A lyrics or nowplaying enabled": "跟随所选音轨：歌词来源启用或正在播放时不可用",
    "Follow selected track (playlist)": "跟随所选音轨（播放列表）",
    "Force update": "强制更新",
    "Freestyle": "自由式",
    "Front": "封面",
    "Heading": "标题",
    "Icon": "图标",
    "Image": "图像",
    "Image ": "图像",
    "Image+text": "图像+文本",
    "Inactivate": "停用",
    "Last.fm Top Albums: ": "Last.fm 热门专辑： ",
    "Last.fm": "Last.fm",
    "Last.fm:": "Last.fm：",
    "Layout": "布局",
    "Left": "左",
    "Load": "加载",
    "Manual cycle: wheel over button": "手动循环：滚动滚轮",
    "Middle click": "中键单击",
    "Missing data": "缺少数据",
    "Mode: ": "模式：",
    "More...": "更多...",
    "More Tags:": "更多标签：",
    " N/A no tags enabled": " 不可用，未启用标签",
    "N/A - requires last.fm photo. Selected image: ": "不可用 - 需要 Last.fm 照片。所选图像： ",
    "No black listed images for current artist": "当前艺术家没有列入黑名单的图像",
    "Open file location": "打开文件位置",
    "Open last edited": "打开上次编辑的项目",
    "Options...": "选项...",
    "Options: see console": "选项：请查看控制台",
    "Overlay": "叠加",
    "Overlay image area": "叠加图像区域",
    "Paste text from clipboard": "从剪贴板粘贴文本",
    "Photo": "照片",
    "Playlists": "播放列表",
    "Prefer both": "首选两个",
    "Prefer composition reviews (allmusic && wikipedia)": "首选作品评论（Allmusic 和 维基百科）",
    "Prefer nowplaying": "首选正在播放项",
    "Reload": "重新加载",
    "Rename custom style...": "重命名自定义样式...",
    "Reset album history...": "重置专辑历史记录...",
    "Reset style...": "重置样式...",
    "Reset to default size...": "重置为默认大小...",
    "Reset zoom": "重置缩放",
    " review": " 评论",
    "Review [allmusic]": "评论 [Allmusic]",
    "Review [last.fm]": "评论 [Last.fm]",
    "Review [wikipedia]": "评论 [维基百科]",
    "Review [allmusic location]": "评论 [AllMusic 位置]",
    "Review [last.fm location]": "评论 [Last.fm 位置]",
    "Review [wikipedia location]": "评论 [维基百科位置]",
    "Right": "正确的",
    "Show album history": "显示专辑历史记录",
    "Show top albums": "显示热门专辑",
    "Show track review options on load menu": "在加载菜单上显示音轨评论选项",
    "Similar Artists:": "相似艺术家：",
    "Sources": "来源",
    "Static": "静态",
    "Summary": "摘要",
    "Tag": "标签",
    "Tag files...": "写入文件标签...",
    "Tagger": "标签",
    "Text": "文本",
    "Top": "上",
    "track": "首",
    "Track": "首",
    "tracks": "首",
    "Tracks [allmusic]": "音轨 [Allmusic]",
    "Tracks [last.fm]": "音轨 [Last.fm]",
    "Tracks [wikipedia]": "音轨 [维基百科]",
    "Type:": "样式：",
    "Undo": "撤消",
    " WARNING: last.fm genre whitelist not found or invalid [try force update - needs internet connection]": " 警告：Last.fm 流派白名单未找到或无效 [尝试强制更新 - 需要互联网连接]",
    "Wikipedia": "维基百科",
    "Write existing file info to tags: ": "将现有文件信息写入标签：",
    "Show similar artists": "显示相似艺术家",
    "Show more tags (circle button if present)": "显示更多标签（如果存在，则为圆圈按钮）",
    "Show artist history": "显示艺术家历史记录",
    "Reset artist history...": "重置艺术家历史记录...",
    "Last.fm: ": "Last.fm：",
    ": similar artists...": "：相似艺术家...",
    ": top albums...": "：热门专辑...",
    "Allmusic: ": "Allmusic：",
    "...": "...",
    "Show top albums": "显示热门专辑",
    "Show album history": "显示专辑历史记录",
    "Reset album history...": "重置专辑历史记录...",
    "+ Add": "+ 添加",
    " main image": " 主图像",
    " to black list: ": "到黑名单：",
    "N/A - no": "不可用 - 无",
    " image file": " 图像文件",
    " - Remove from black list (click name): ": " - 从黑名单中删除（点击名称）："
}
`

**Comment by SyaoranChang** [comment]
I think allmusic should not need to be translated until there is an official Chinese Name

const traditionalChinese = {
	"+ Add to black list: ": "+ 加入到黑名單： ",
	": N/A no playlist tracks selected": ": N/A 未選擇播放列表的曲目", // added
	"Activate biography": "啟用傳記", // added
	"Album": "專輯",
	"Album History:": "專輯歷史紀錄：",
	"album look-up": "專輯查詢", // added
	"Album review [allmusic]": "專輯評論 [allmusic]", // added
	"Album review [last.fm]": "專輯評論 [last.fm]", // added
	"Album review [wikipedia]": "專輯評論 [維基百科]", // added
	"Photos [last.fm]": "照片 [last.fm]", // added
	"Album Unknown": "專輯不詳", // added
	"Album view": "專輯檢視",
	"Align with text": "與文字對齊",
	"Alignment": "對齊方式",
	"Alignment horizontal": "水平對齊", // added
	"Alignment vertical": "垂直對齊", // added
	"All tagger settings...": "所有標籤編輯器設置...", // added
	"Allmusic": "Allmusic", // added
	"Allmusic:": "Allmusic：",
	"Alt+Click": "Alt+點擊",
	"Alt+Middle click": "Alt+點擊中鍵",
	"Amalgamate": "合併",
	"Artist": "表演者",
	"Artist (single image [fb2k: display])": "表演者（單一圖片 [fb2k: 顯示]）", // added display
	"Artist History:": "表演者歷史紀錄：",
	"artist look-up": "表演者查詢", // added
	"Artist Unknown": "表演者不詳", // added
	"Artist view": "表演者檢視",
	"Auto cycle": "自動循環",
	"Auto cycle items": "自動循環項目",
	"Auto lock": "自動鎖",
	"Auto-fallback": "自動回退",
	"Back": "後面",
	" biography": " 傳記", // added
	"Biography [allmusic]": "傳記 [allmusic]",
	"Biography [last.fm]": "傳記 [last.fm]",
	"Biography [wikipedia]": "傳記 [維基百科]",
	"Biography [allmusic location]": "傳記 [allmusic 位置]", // added
	"Biography [last.fm location]": "傳記 [last.fm 位置]", // added
	"Biography [wikipedia location]": "傳記 [維基百科位置]", // added
	"Black list": "黑名單",
	"Bottom": "底部",
	"Cancel": "取消", // added
	"Centre": "中心",
	"Click": "點擊",
	"composition loaded": "作品載入", // added
	"Composition Unknown": "作品不詳", // added
	"Configure...": "設置...", // added
	"Cover": "封面",
	"Create && manage styles": "建立和管理樣式",
	"Create new style...": "建立新樣式...",
	"Cycle above": "循環以上",
	"Cycle from custom folder [fallback to above]": "從自訂文件夾循環 [自動退回上面]",
	"Cycle from download folder": "從下載資料夾循環",
	"Cycle from folder": "從資料夾循環",
	"Delete custom style...": "刪除自定義的樣式...",
	"Disc": "光碟",
	"Display": "顯示",
	"Double click": "雙擊", // added
	"Export custom style...": "匯出自定義的樣式...",
	"Filmstrip": "幻燈片",
	" first": " 第一的", // added
	"Follow selected track: N/A lyrics or nowplaying enabled": "跟隨所選曲目：N/A 歌詞或正在播放已啟用", // added
	"Follow selected track (playlist)": "跟隨選擇的曲目（播放列表）",
	"Force update": "強制更新",
	"Freestyle": "自由風格",
	"Front": "前面",
	"Heading": "標題",
	"Icon": "圖示",
	"Image": "圖片",
	"Image ": "圖片 ",
	"Image+text": "圖片+文字",
	"Inactivate": "停用", // added
	"Last.fm Top Albums: ": "Last.fm 熱門專輯： ",
	"Last.fm": "Last.fm", // added
	"Last.fm:": "Last.fm：",
	"Layout": "佈局",
	"Left": "左側",
	"Load": "載入",
	"Manual cycle: wheel over button": "手動循環: 滑鼠滾輪按鈕",
	"Middle click": "點擊中鍵",
	"Missing data": "缺失數據", // added
	"Mode: ": "模式：", // added
	"More...": "更多...",
	"More Tags:": "更多標籤：", // added
	" N/A no tags enabled": " N/A 未啟用標籤", // added
	"N/A - requires last.fm photo. Selected image: ": "N/A - 需要 last.fm 照片。 選擇的圖片： ",
	"No black listed images for current artist": "目前的表演者沒有黑名單的圖片",
	"Open file location": "開啟所在資料夾",
	"Open last edited": "開啟上次編輯", // added
	"Options...": "設定...",
	"Options: see console": "設定： 查看主控台", // added
	"Text overlay": "文字疊加",
	"Overlay image area": "疊加圖像區域",
	"Paste text from clipboard": "從剪貼簿貼上文字", //added
	"Photo": "照片",
	"Playlists": "播放列表", // added
	"Prefer both": "兩者都喜歡",
	"Prefer composition reviews (allmusic && wikipedia)": "比較喜歡作品評論（allmusic 和 維基百科）",
	"Prefer nowplaying": "比較喜歡現在播放",
	"Reload": "重新載入",
	"Rename custom style...": "重新命名自定義的樣式...",
	"Reset album history...": "重置專輯歷史紀錄...",
	"Reset style...": "重置樣式...",
	"Reset to default size...": "重置為預設大小...",
	"Reset zoom": "重置縮放",
	" review": " 評論", // added
	"Review [allmusic]": "評論 [allmusic]",
	"Review [last.fm]": "評論 [last.fm]",
	"Review [wikipedia]": "評論 [維基百科]",
	"Review [allmusic location]": "評論 【allmusic 位置】", // added
	"Review [last.fm location]": "評論 [last.fm 位置]", // added
	"Review [wikipedia location]": "評論 [維基百科位置]", // added
	"Right": "右側",
	"Show album history": "顯示專輯歷史紀錄",
	"Show top albums": "顯示熱門專輯",
	"Show track review options on load menu": "在載入選單上顯示曲目評論選項",
	"Similar Artists:": "相似的表演者：",
	"Sources": "來源",
	"Static": "靜態",
	"Summary": "摘要",
	"Tag": "標籤", // added
	"Tag files...": "標籤檔案...", // added
	"Tagger": "標籤編輯器", // added
	"Text": "文字",
	"Top": "頂部",
	"track": "曲目", // added
	"Track": "曲目", // correct?
	"tracks": "曲目", // added
	"Tracks [allmusic]": "曲目 [allmusic]",
	"Tracks [last.fm]": "曲目 [last.fm]",
	"Tracks [wikipedia]": "曲目 [維基百科]",
	"Type:": "類型：",
	"Undo": "還原", // added
	" WARNING: last.fm genre whitelist not found or invalid [try force update - needs internet connection]": " 警告：未找到 last.fm 類型白名單或無效 [嘗試強制更新 - 需要網路連接]", // added
	"Wikipedia": "維基百科", // added
	"Write existing file info to tags: ": "將現有文件信息寫入標籤：", // added
	"Show similar artists": "顯示相似的表演者", // added
	"Show more tags (circle button if present)": "顯示更多標籤（如果有圓圈按鈕）", // added
	"Show artist history": "顯示表演者歷史紀錄", // added
	"Reset artist history...": "重置表演者歷史紀錄...", // added
	"Last.fm: ": "Last.fm: ", // added
	": similar artists...": "：相似的表演者...", // added
	": top albums...": "：熱門專輯...", // added
	"Allmusic: ": "Allmusic： ", // added
	"...": "...", // added
	"Show top albums": "顯示熱門專輯", // added
	"Show album history": "顯示專輯歷史紀錄", // added
	"Reset album history...": "重置專輯歷史紀錄...",
	"+ Add": "+ 增加", // added
	" main image": " 主要圖像", // added
	" to black list: ": " 加入黑名單： ", // added
	"N/A - no": "N/A - 無", // added
	" image file": " 圖片檔案", // added
	" - Remove from black list (click name): ": " - 從黑名單中刪除（點擊名稱）： " // added
}

**Comment by Wil-B** [comment]
This is all implemented and will be in the next version.

**Pull request closed without merging**
